### ISSUE TITLE
for color/image processing, replace miniexif-tool with ruby-vips if possible

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/assembly-objectfile#72]
See also sul-dlss/assembly-image/issues/54

Look for the code that uses exif and see what can be replaced. If all of it - yay! Make a PR. If some of it, confer with Tony C as to when we should favor one tool over the other.

Tony C. is the PO for this work, and this ticket should get Tony's approval, not Andrew's.

Note that autodetection of mime type could introduce errors that Image-Magick (or libvips?) could barf on, for example.

**Comment by andrewjbtw** [comment]
Is this about any mimetype detection or just image processing? Issues with mimetypes can cause downstream problems with Access systems. If we're changing how mimetypes are detected, we'll need to look at what happens with text and media files as well as image files.

**Comment by ndushay** [comment]
> Is this about any mimetype detection or just image processing? Issues with mimetypes can cause downstream problems with Access systems. If we're changing how mimetypes are detected, we'll need to look at what happens with text and media files as well as image files.

I'm not sure exactly what this is about yet;  I'll know more soon.  Duly noted on the testing needed.

**Comment by ndushay** [comment]
The focus of replacing the use of mini-exiftool is around the jp2 creation work, NOT around mimetypes.

So the action for this ticket is to determine if there are any methods in assembly-objectfile that would benefit from using ruby-vips instead of mini-exiftool.   (Perhaps not)

**Comment by ndushay** [comment]
To use `libvips` for assembly-object would require it to be installed on VMs for the following apps:

- [x] common-accessioning
- [ ] gis-robot-suite (kurma VMs, I believe?)
- [ ] pre-assembly (see issue sul-dlss/pre-assembly#974)
- [ ] sdr-api
- [x] was-robot-suite

### height and width

height and width are currently computed as part of `Assembly::ContentMetadata::File`, which _may_ not be needed HERE after we switch to cocina structural for
- [ ] common-accessioning (PR sul-dlss/common-accessioning#919)
- [ ] gis-robot-suite (see PRsul-dlss/gis-robot-suite/pull/515)
- [ ] pre-assembly (see sul-dlss/pre-assembly#1002)
- [ ] sdr-api - not sure if it needs it??
- [ ] was-robot-suite - improving thumbnail generation is part of June-July 2022 work cycle

but would instead be needed in those code bases, if they are creating their own cocina structural -- which raises the separate question ... would it make more sense for THIS gem to have the code to create cocina structural

### color stuff

`object_file.has_color_profile?`
